/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package address.formatter;

public class App {
    public static void main(String[] args) {
        String input = String.join(" ", args);
        IParser parser = new ParserResolver().resolve(input);
        Address parse = parser.parse();
        System.out.println(parse.toString());
    }
}
